---
title: "Problema 7 (Promethee)"
author: "Alicia Casaux Vazquez"
date: "2024-10-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("teoriadecision_funciones_multicriterio_diagram.R")
source("teoriadecision_funciones_multicriterio_utiles.R")
source("teoriadecision_funciones_multicriterio.R")
```


```{r}
p7 = multicriterio.crea.matrizdecision(c (100,15,7,40,-50,
                                          200,25,7,60, -200,
                                          100,20,4,25, -25,
                                          200,30,20,70, -350,
                                          250,25,15,100,-500) ,
                                       numalternativas = 5,numcriterios = 5)

pesos.criterios = c(0.25/1.1,0.25/1.1,0.2/1.1,0.2/1.1,0.2/1.1)

tab.fpref = matrix(c(1,0,0,0,
                      1,0,0,0,
                      1,0,0,0,
                      1,0,0,0,
                      1,0,0,0) ,ncol=4,byrow=T)
```

# PROMETHEE I
```{r}
tab.Pthee.i = multicriterio.metodo.promethee_i(p7,pesos.criterios,tab.fpref)
tab.Pthee.i

require ("qgraph") 
qgraph(tab.Pthee.i$tablarelacionsupera)
```

# PROMETHEE II

```{r}
tab.Pthee.ii = multicriterio.metodo.promethee_ii(p7,pesos.criterios,tab.fpref)
tab.Pthee.ii 

qgraph(tab.Pthee.ii$tablarelacionsupera)
```

# PROMETHEE I (medias)

```{r}
tab.Pthee.i_med = multicriterio.metodo.promethee_i_med(p7,pesos.criterios,tab.fpref)
tab.Pthee.i_med

qgraph (tab.Pthee.i_med$tablarelacionsupera)
```

# PROMETHEE II (medias)
```{r}
tab.Pthee.ii_med = multicriterio.metodo.promethee_ii_med(p7,pesos.criterios,tab.fpref)
tab.Pthee.ii_med

qgraph (tab.Pthee.ii_med$tablarelacionsupera)
```

# Ordenación final alternativas Mét. Promethee II (medias)
```{r}
order(tab.Pthee.ii_med$vflujos.netos,decreasing = T)
```

# Comparativa Promethee II: sin medias y con medias
```{r}
order (tab.Pthee.ii$vflujos.netos,decreasing = T)
order (tab.Pthee.ii_med$vflujos.netos,decreasing = T)
```

# Resolución con Promethee Windows
```{r}
res = multicriterio.metodo.promethee_windows(p7, tab.fpref, pesos.criterios)
res = multicriterio.metodo.promethee_windows (p7, tab.fpref, pesos.criterios,
fminmax = c("max", "max", "max", "max","min"))

res02 = multicriterio.metodo.promethee_windows_kableExtra(res)
res02$tabEscenario
res02$tabAcciones
rownames(res$Acciones)
```




